"""Runtime helpers for packaging research strategies.

The wheel generated by :mod:`fe.export.build` exposes an abstract base class
named :class:`polymarket_alpha.Strategy`.  During local research we do not have
the production package installed, so this module provides a lightweight shim
that mirrors the runtime API.  Strategy adapters can safely import
``RuntimeStrategy`` which resolves to the wheel implementation when available
and otherwise falls back to an equivalent local definition.

In addition to the base class this module includes small utilities that make it
easy for adapters to accept flexible inputs (mappings, records or full
``pandas`` data frames) while still delegating to the research functions.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Iterable, Mapping, MutableSequence, Sequence

import pandas as pd

try:  # pragma: no cover - exercised when the wheel is installed.
    from polymarket_alpha import Strategy as _RuntimeStrategy
except ImportError:  # pragma: no cover - used in the research tree.
    class _RuntimeStrategy(ABC):
        """Fallback implementation matching the production interface."""

        @abstractmethod
        def propose_orders(self, market_state: Any) -> Any:
            """Return orders for the provided market state."""

        @abstractmethod
        def on_fill(self, fill: Mapping[str, Any]) -> Any:
            """Observe a fill event produced by the exchange."""

        @abstractmethod
        def risk_profile(self) -> Mapping[str, Any]:
            """Return risk controls advertised by the strategy."""


class RuntimeStrategy(_RuntimeStrategy):
    """Concrete base class used by adapters inside the repo."""

    def __init__(self) -> None:
        self._fills: MutableSequence[Mapping[str, Any]] = []

    def on_fill(self, fill: Mapping[str, Any]) -> Mapping[str, Any]:
        """Record ``fill`` and echo the running history."""

        self._fills.append(dict(fill))
        return {"fills": list(self._fills)}


def ensure_dataframe(data: Any, *, columns: Iterable[str] | None = None) -> pd.DataFrame:
    """Coerce *data* into a :class:`pandas.DataFrame`.

    The adapters are designed to operate on the same tabular structures used in
    research notebooks.  To remain ergonomic we accept a variety of inputs:

    - an existing :class:`DataFrame`
    - a mapping describing a single row
    - an iterable of mappings representing multiple rows

    Parameters
    ----------
    data:
        Source object containing market observations.
    columns:
        Optional list of columns that must be present in the resulting frame.
    """

    if isinstance(data, pd.DataFrame):
        df = data.copy()
    elif isinstance(data, Mapping):
        df = pd.DataFrame([data])
    elif isinstance(data, Sequence):
        if not data:
            df = pd.DataFrame()
        elif isinstance(data[0], Mapping):
            df = pd.DataFrame(list(data))
        else:
            raise TypeError("Sequence inputs must contain mapping elements")
    else:
        raise TypeError(
            "market_state must be a DataFrame, a mapping or a sequence of mappings"
        )

    if columns is not None:
        missing = [col for col in columns if col not in df.columns]
        if missing:
            raise KeyError(f"Missing required columns: {missing}")
    return df


def latest_row(df: pd.DataFrame) -> pd.Series:
    """Return the most recent row from ``df``.

    Raises ``ValueError`` when the frame is empty to provide a friendlier error
    message than ``IndexError``.
    """

    if df.empty:
        raise ValueError("market_state must contain at least one observation")
    return df.iloc[-1]


__all__ = ["RuntimeStrategy", "ensure_dataframe", "latest_row"]
